FROM node
WORKDIR /usr/src/app
COPY package.json .
RUN npm install && npm install -g mocha
RUN mv /usr/src/app/node_modules /usr/src/node_modules
COPY app.js .
COPY routers ./routers
COPY tests ./tests
EXPOSE 80
CMD ["npm", "test"]